//
//  questions.swift
//  Nice to Meet You
//
//  Created by Ike Mattice on 1/2/17.
//  Copyright © 2017 Ike Mattice. All rights reserved.
//

var questions: [String] = [
    "What do you value most in a friendship?",
    "What is one of your pet peeves?",
    "If you were a ghost, what would you do?",
    "When do you feel the most confident and why?",
//]
//
//var photoQuestions = [
    "What is the one thing you would like to change about yourself?",
    "What is on your bucket list for the next 365 days?",
    "What is an ideal weekend for you?",
    "If you had to choose to live without one of your five senses, which would you give up?",
    "What is your idea of the perfect first date?",
//  ]
//
//var morequestions = [
    "Which parent are you closer to and why?",
    "When was the last time you broke someone’s heart?",
    "What is the one thing that people always misunderstand about you?",
    "What did your past relationship teach you?",
    "If a genie granted you 3 wishes right now, what would you wish for?",
    "What is something that you regret?",
    "What do you think about when you’re by yourself?",
    "If you could get away with one crime, would you?  What would it be?",
    "What animal best represents you?  What charactoristics do you share?",
    "Where would you like to see yourself in 5 years?",
    "If you could live forever, how would you spend your time?",
    "Why did you choose your profession?",
    "In what ways do you hold yourself back?",
    "What was your dream job growing up?",
    "What was your greatest failure?  How did you overcome it?",
    "What has been your greatest achivement? How has it shaped you?",
    "If you could master one skill you do not have right now, what would it be?",
    "What would be your perfect day?",
    "If you could have one superpower, what would it be and how would you use it?",
    "If you could speak another language, which would it be and why?",
    "What makes you happiest?",
    "What, if anything, is too serious to be joked about?",
    "In what ways are you the same as your childhood self?",
    "If you could play one instrument you are not able to play right now, what would it be and why?",
    "What is your favorite holiday and why?",
    "What is your fondest childhood memory?",
    "If you could abolish one piece of modern technology, what would it be and why?",
    "If your house was burning and you could only save one item, what would it be and why?",
    "What words of wisdom would you pass along to your childhood self?",
    "Who is your oldest friend?  Why are they your friend?",
    "What is the most fun you've had this week?",
    "What is your least favorite food?",
    "Describe the worst roommate you've ever had.",
    "How would you describe yourself in 5 words?  No more.  No less.",
    "What is your worst habit?",
    "What is the weirdest talent that you have?",
    
    "Would you rather read an eBook or a paper book?  Why?",
    "Would you rather go to a play or musical?  Why?",
    "Would you rather go to a live theatre performance or a movie? Why?",
    "Would you rather hike or bike?  Why?",
    "Would you rather travel by plane, train, or automobile? Why?",
    "Would you rather go to a comedy club or a dance club?  Why?",
    "Would you prefer an evening in or a night out?  Why?",
    "Do you prefer Facebook or Twitter?  Why?",
    "Would you rather win the lottery or find your perfect job?",
    
    "If money were no object, what would you do all day?",
    "What was your favorite activity in gym class?",
    "Who is your favorite author?",
    "What has been your favorite challenge?",
    "What is one thing that should be taught in school that isn't already?",
    "What are 5 things someone would immediately notice if they walked in your front door?",
    "What was your upbringing like?",
    "What's on your bucket list?",
    "What makes you wildly happy?",
    "What are your top 3 fears?",
    "Which parent are you most like?",
    "What has been your most recent big life change?",
    "How do you handle anger?",
    "Given the choice of anyone in the world, whom would you want as a dinner guest?",
    "Would you like to be famous?  In what way?",
    "When did you last sing to yourself?  When did you last sing to someone else?",
    "If you could change anything about the way you were raised, what would it be?",
    "Alternate sharing 5 characteristics you look for in a friend or partner.",
    "Alternate sharing 5 positive features about each other.",
    "How close is your family?",
    "Make 3 true statements starting with the word \"we\".",
    "Complete the sentence: \"I wish I had someone with whom I could share...\"",
    "Share an embarassing moment in your life.",
    "When did you last cry in front of another person?  By yourself?  Why?",
    "Share something you like about each other already.",
    "Share a personal problem and ask each other for advice on how to handle it.",
    //"While on a trip to another city, your spouse/lover meets and spends a night with an exciting stranger. Given that they will never meet again, and could never otherwise learn of the incident, would you want your partner to tell you about it?",
    "What is the biggest complaint about your job?",
    "Have you ever had a nickname?  What is it and how did you obtain it?",
    "What is the craziest thing you've ever done in the name of love?",
    "What was your favorite subject in school?",
    "Do you collect anything?",
    "Which of your five senses would you say is your strongest? Why?",
    "What do you do to keep fit?",
    "What are 3 things you think of most each day?",
    "If you had a warning label, what would yours say?",
    "Who was your first crush?",
    "What is the most interesting thing you can see out of your office window?",
    "On a scale of 1-10, how funny would you say you are?",
    "What is the one thing you will never do again?",
    "Who knows you the best?",
    "Name 3 things you appear to have in common with each other.",
    "What are your 3 biggest character flaws?",
    "What is the biggest character turn-off for you?",
    "What is the hardest thing you have ever done?",
    "Would you rather lose all of your memories or never be able to make new ones?",

]
